"""Dat

Revision ID: 4b4ee54796fc
Revises: 933607e875bf
Create Date: 2024-10-05 18:20:20.996281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4ee54796fc'
down_revision: Union[str, None] = '933607e875bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('countSec', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'countSec')
    # ### end Alembic commands ###
